// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_new_key_pair`, `generate_new_mnemonic`, `get_gossipsub_config`, `get_keypair_from_mnemonic_str`, `get_keypair_from_mnemonic`, `get_mnemonic_from_str`, `get_note`, `get_peer_id`, `main1`, `publish_message`, `set_note`
// These types are ignored because they are not used by any `pub` functions: `MyBehaviourEvent`, `MyBehaviour`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `fmt`, `handle_established_inbound_connection`, `handle_established_outbound_connection`, `handle_pending_inbound_connection`, `handle_pending_outbound_connection`, `on_connection_handler_event`, `on_swarm_event`, `poll`

String greet({required String name}) =>
    RustLib.instance.api.crateApiMainGreet(name: name);

String test1() => RustLib.instance.api.crateApiMainTest1();

String test4() => RustLib.instance.api.crateApiMainTest4();

Stream<int> tick() => RustLib.instance.api.crateApiMainTick();

Stream<CustomResponseEvent> runApp() =>
    RustLib.instance.api.crateApiMainRunApp();

class CustomResponseEvent {
  final Map<String, List<Map<String, String>>> data;

  const CustomResponseEvent({
    required this.data,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<CustomResponseEvent> newInstance() =>
      RustLib.instance.api.crateApiMainCustomResponseEventNew();

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CustomResponseEvent &&
          runtimeType == other.runtimeType &&
          data == other.data;
}
