// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_note`, `main1`, `new`, `set_note`
// These types are ignored because they are not used by any `pub` functions: `NoteStorage`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String greetMe({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreetMe(name: name);

String test1() => RustLib.instance.api.crateApiSimpleTest1();

String test4() => RustLib.instance.api.crateApiSimpleTest4();

Stream<int> tick() => RustLib.instance.api.crateApiSimpleTick();
