// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:cross_clip/src/rust/api/main.dart';

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_note`, `main1`, `set_note`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiMainGreet(name: name);

Stream<int> tick() => RustLib.instance.api.crateApiMainTick();

Stream<CustomResponseEvent> swarmEventStream() =>
    RustLib.instance.api.crateApiMainRunApp();

class NoteStorage {
  final Map<String, List<Map<String, String>>> data;

  const NoteStorage({
    required this.data,
  });

  // // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  // static Future<SwarmEvent> newInstance() =>
  //     RustLib.instance.api.crateApiMainSwarmEventNew();

  @override
  int get hashCode => data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteStorage &&
          runtimeType == other.runtimeType &&
          data == other.data;
}
