// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.4.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'simple.dart';

// These functions are ignored because they are not marked as `pub`: `create_new_key_pair`

Future<void> runSwarm({required NoteStorage noteStorage}) =>
    RustLib.instance.api.crateApiSwamMainRunSwarm(noteStorage: noteStorage);
